language: generic
sudo: false

addons:
  apt:
    packages:
    - python-qt4
    - python-qt4-dev
    - ccache
    - cmake
    - zlib1g-dev
    - libpng-dev
    - libfreetype6-dev

env:
  global:
    - INSTALL_EDM_VERSION=1.9.2
      PYTHONUNBUFFERED="1"

matrix:
  include:
  - env: RUNTIME=2.7
  - env: RUNTIME=3.5
  fast_finish: true

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.cache
    - $HOME/.ccache

before_install:
  - ccache -s
  - mkdir -p "${HOME}/.cache/download"
  - ci/install-edm.sh
  - export PATH="${HOME}/edm/bin:/usr/lib/ccache:${PATH}"
  - edm install -y click
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - edm run -- python -m ci install --runtime=${RUNTIME}
script:
  - edm run -- python -m ci test --runtime=${RUNTIME}
