name: Run tests

on: [pull_request, workflow_dispatch]

env:
  INSTALL_EDM_VERSION: 3.4.0

jobs:
  tests:
    strategy:
      matrix:
        runtime: ['3.6']
        os: ['ubuntu-latest']

    runs-on: ${{ matrix.os }}

    steps:
    - name: Clone the source
      uses: actions/checkout@v3
    - name: Install Qt dependencies for Linux
      run: |
        sudo apt-get update
        sudo apt-get install qt5-default
        sudo apt-get install libxkbcommon-x11-0
        sudo apt-get install libxcb-icccm4
        sudo apt-get install libxcb-image0
        sudo apt-get install libxcb-keysyms1
        sudo apt-get install libxcb-randr0
        sudo apt-get install libxcb-render-util0
        sudo apt-get install libxcb-xinerama0
        sudo apt-get install pulseaudio
        sudo apt-get install libpulse-mainloop-glib0
        sudo apt-get install libopengl0
      if: runner.os == 'Linux'
    - name: Set up EDM
      uses: enthought/setup-edm-action@v1
      with:
        edm-version: ${{ env.INSTALL_EDM_VERSION }}
    - name: Set up bootstrap Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install click to the bootstrap environment
      run: python -m pip install click
    - name: Install test environment
      run: python -m ci install --runtime=${{ matrix.runtime }}
    - name: Run tests
      run: python -m ci test --runtime=${{ matrix.runtime }}
