name: Run tests

on: [pull_request, workflow_dispatch]

jobs:
  tests:
    strategy:
      matrix:
        runtime: ['3.6', '3.8']
        os: ['ubuntu-latest']

    runs-on: ${{ matrix.os }}

    steps:
    - name: Clone the source
      uses: actions/checkout@v3
    - name: Set up EDM
      uses: enthought/setup-edm-action@v1
      with:
        edm-version: ${{ env.INSTALL_EDM_VERSION }}
    - name: Set up bootstrap Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install click to the bootstrap environment
      run: python -m pip install click
    - name: Install test environment
      run: python -m ci install --runtime=${{ matrix.runtime }}
    - name: Run tests
      run: python -m ci test --runtime=${{ matrix.runtime }}
